# Generated by Django 3.2.8 on 2021-10-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211008_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='classes',
            name='color',
            field=models.IntegerField(default=1),
        ),
    ]
