# Generated by Django 3.2.8 on 2021-10-11 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20211008_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='classcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='documentcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='classes',
        ),
        migrations.AddField(
            model_name='classes',
            name='assignments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.assignment'),
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.profile'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classes',
            name='color',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='classes',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doc',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doc',
            name='text',
            field=models.TextField(default='File Text'),
        ),
        migrations.AddField(
            model_name='classes',
            name='code',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.classcode'),
        ),
        migrations.AddField(
            model_name='doc',
            name='code',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.documentcode'),
        ),
    ]
