# Generated by Django 3.2.7 on 2021-10-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_classes_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='assignments',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.profile'),
        ),
    ]
