# Generated by Django 3.2.7 on 2021-10-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20211012_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='assignments',
        ),
        migrations.AddField(
            model_name='classes',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.classcode'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='main.profile'),
        ),
    ]
