# Generated by Django 3.2.7 on 2021-10-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211012_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, to='main.profile'),
        ),
    ]
