# Generated by Django 3.2.7 on 2021-10-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211012_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='codestr',
            field=models.CharField(default='', max_length=6),
        ),
    ]
