# Generated by Django 3.2.8 on 2021-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_classes_codestr'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='ownerstr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
