# Generated by Django 3.2.7 on 2021-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_classes_ownerstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.CharField(default='', max_length=10),
        ),
    ]
