# Generated by Django 3.2.8 on 2021-10-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_classes_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='discription',
            new_name='description',
        ),
    ]
