# Generated by Django 3.2.8 on 2021-10-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_discription_classes_description'),
    ]

    operations = [
       
    ]
