# Generated by Django 3.2.8 on 2021-10-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211019_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmentcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=17)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='text',
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(default='Instructions'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='pointValue',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignmentcode',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.assignmentcode'),
        ),
    ]
