# Generated by Django 3.2.8 on 2021-10-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_assignmentcode_assignment_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='doccode',
            new_name='code',
        ),
    ]
