# Generated by Django 3.2.8 on 2021-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_doccode_doc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
