# Generated by Django 3.2.8 on 2021-10-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_assignment_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='codestr',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ownerstr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
