# Generated by Django 3.2.8 on 2021-10-20 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_auto_20211020_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assignment',
            new_name='assignmentObj',
        ),
    ]
