# Generated by Django 3.2.8 on 2021-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_assignmentobj_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentobj',
            name='submissions',
            field=models.ManyToManyField(blank=True, to='main.doc'),
        ),
    ]
