# Generated by Django 3.2.8 on 2021-10-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211025_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='submissionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
