# Generated by Django 3.2.8 on 2021-10-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_doc_submissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='codestr',
            field=models.CharField(default='', max_length=30),
        ),
    ]
