# Generated by Django 3.2.8 on 2021-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_doc_codestr'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='comment',
            field=models.TextField(default='File Text'),
        ),
        migrations.AddField(
            model_name='doc',
            name='pointValue',
            field=models.IntegerField(default='-1'),
        ),
    ]
