# Generated by Django 3.2.8 on 2021-10-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20211027_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
