# Generated by Django 3.2.8 on 2021-10-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20211027_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentobj',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
