# Generated by Django 3.2.7 on 2021-11-22 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0033_assignmentobj_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='assignmentTagsNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagsNum',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentobj',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.AssignmentTags'),
        ),
        migrations.AddField(
            model_name='classes',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tags'),
        ),
    ]
