# Generated by Django 3.2.7 on 2021-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211122_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentobj',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.assignmentTags'),
        ),
    ]
