# Generated by Django 3.2.7 on 2021-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_assignmentobj_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentobj',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.assignmentTags'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
