# Generated by Django 3.2.7 on 2021-11-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20211122_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignmentobj',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.assignmentTags'),
        ),
    ]
