# Generated by Django 3.2.7 on 2021-12-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211130_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentobj',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentobj',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.assignmentTags'),
        ),
    ]
